on: [workflow_dispatch]
jobs:
  liveness_github_actions:
    runs-on: ubuntu-latest
    name: check liveness github actions
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.7.3
      - name: Check bb runs
        run: bb --version
      - name: liveness
        working-directory: ./.github/scripts/liveness
        run: bb run --parallel liveness
      - name: Get the script output
        run: echo "${{ steps.liveness.outputs }}"
