on: [workflow_dispatch]
jobs:
  liveness_github_actions:
    runs-on: ubuntu-latest
    name: check liveness github actions
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: babashka script
        uses: tzafrirben/babashka-docker-action@v0.3
        id: bb_script
        with:
          bb_src: "./.github/scripts/liveness"
          bb_args: "run --parallel liveness"
      - name: Get the script output
        run: echo "${{ steps.bb_script.outputs.bb_out }}"
